"""add photograph column to users table

Revision ID: 0f9ed2a6f8f7
Revises: ba451380196a
Create Date: 2024-04-29 09:36:57.844068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f9ed2a6f8f7'
down_revision = 'ba451380196a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photograph', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('photograph')

    # ### end Alembic commands ###
