"""empty message

Revision ID: 3d969a91fda7
Revises: f74cac455736
Create Date: 2024-10-24 10:42:49.022128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d969a91fda7'
down_revision = 'f74cac455736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('thekey', sa.String(length=255), nullable=False),
    sa.Column('thevalue', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('setting_id'),
    sa.UniqueConstraint('thekey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
